import './Osseus/CSS/_config.css'
import './Osseus/CSS/_custom.css'
import './Osseus/CSS/color.css'
import './Osseus/CSS/reset.css'
import './Osseus/CSS/structure.css'
import './Osseus/CSS/utility.css'
import './Osseus/CSS/typography.css'
